/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktool_NDKTool */

#ifndef _Included_com_example_ndktool_NDKTool
#define _Included_com_example_ndktool_NDKTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktool_NDKTool
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktool_NDKTool_getStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
