/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktool_NDKTool */

#ifndef _Included_com_example_ndktool_NDKTool
#define _Included_com_example_ndktool_NDKTool
#ifdef __cplusplus
extern "C" {  // 用c来编，防止函数重载问题
#endif
/*
 * Class:     com_example_ndktool_NDKTool
 * Method:    getStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktool_NDKTool_getStringFromJni
  (JNIEnv *, jclass);

JNIEXPORT jint JNICALL
Java_com_example_ndktool_NDKTool_getDirSizeByNative(JNIEnv *env, jclass clazz, jstring path);

#ifdef __cplusplus
}
#endif
#endif
